#!/usr/bin/env node
/**
 * Setup and verification script for vscode-stdio-monitor skill in OpenClaw.
 * Saves configuration to .env and verifies connectivity through Cloudflare Access and WebSocket.
 *
 * Designed to be invoked via OpenClaw chat or CLI during skill registration.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { URL } = require('url');

let WebSocket;
try {
  WebSocket = require('ws');
} catch {
  // WebSocket will be skipped if ws is not installed yet
}

// Parse CLI arguments
const args = process.argv.slice(2);
const params = {};

for (let i = 0; i < args.length; i++) {
  if (args[i].startsWith('--')) {
    const key = args[i].replace(/^--/, '');
    const val = args[i + 1] && !args[i + 1].startsWith('--') ? args[++i] : 'true';
    params[key] = val;
  }
}

// Support multiple alias variants commonly generated by LLM agents in chat
const rawHost =
  params.host ||
  params.url ||
  params['vscode-url'] ||
  params.vscodeUrl ||
  params['base-url'] ||
  params.baseUrl ||
  process.env.VSCODE_HOST ||
  process.env.VSCODE_URL;

const clientId =
  params['client-id'] ||
  params.clientId ||
  params.client_id ||
  params.id ||
  process.env.CF_ACCESS_CLIENT_ID ||
  '';

const clientSecret =
  params['client-secret'] ||
  params.clientSecret ||
  params.client_secret ||
  params.secret ||
  process.env.CF_ACCESS_CLIENT_SECRET ||
  '';

const directMode = params.direct === 'true' || params['no-proxy'] === 'true';
const checkOnly = params['check-only'] === 'true' || params['dry-run'] === 'true';
const jsonOnly = params.json === 'true';

function log(msg) {
  if (!jsonOnly) {
    console.log(msg);
  }
}

function errorLog(msg) {
  if (!jsonOnly) {
    console.error(msg);
  }
}

if (!rawHost) {
  const usage = {
    success: false,
    error: 'Missing host/url parameter.',
    usage: 'node scripts/setup.js --host <URL> [--client-id <ID>] [--client-secret <SECRET>] [--direct]',
    examples: [
      'node scripts/setup.js --host "https://vscode.yourdomain.com" --client-id "xxx" --client-secret "yyy"',
      'node scripts/setup.js --host "http://127.0.0.1:8090"'
    ],
    chatPrompt: 'Please provide your VS Code Server URL, and optional Cloudflare Access Client ID & Secret.'
  };
  console.error(JSON.stringify(usage, null, 2));
  process.exit(1);
}

// Normalize base URL
let cleanedHost = rawHost.trim().replace(/\/+$/, '');
if (!cleanedHost.startsWith('http://') && !cleanedHost.startsWith('https://')) {
  cleanedHost = `https://${cleanedHost}`;
}

let parsedUrl;
try {
  parsedUrl = new URL(cleanedHost);
} catch (err) {
  console.error(JSON.stringify({
    success: false,
    error: `Invalid URL format: ${err.message}`
  }));
  process.exit(1);
}

let httpBaseUrl = cleanedHost;

// If connecting to code-server without a port, append /proxy/8090 unless --direct is used
if (!directMode) {
  const hasExplicitPort = Boolean(parsedUrl.port);
  const hasProxyPath = parsedUrl.pathname.includes('/proxy/');

  if (!hasExplicitPort && !hasProxyPath) {
    httpBaseUrl = `${cleanedHost}/proxy/8090`;
  }
}

// Normalize trailing slash removal for HTTP
httpBaseUrl = httpBaseUrl.replace(/\/+$/, '');

// Derive WebSocket URL
const wsBaseUrl = httpBaseUrl.replace(/^http:\/\//i, 'ws://').replace(/^https:\/\//i, 'wss://') + '/';

// Skill directory (root of skill)
const skillDir = path.resolve(__dirname, '..');
const envPath = path.join(skillDir, '.env');

// Save to .env unless dry-run
if (!checkOnly) {
  const envContent = `# VS Code Stdio Monitor Skill Configuration
VSCODE_HTTP_URL=${httpBaseUrl}
VSCODE_MONITOR_URL=${wsBaseUrl}
CF_ACCESS_CLIENT_ID=${clientId}
CF_ACCESS_CLIENT_SECRET=${clientSecret}
`;

  try {
    fs.writeFileSync(envPath, envContent, 'utf-8');
    log(`[*] Configuration saved to: ${envPath}`);
  } catch (err) {
    errorLog(`[!] Warning: Failed to write .env (${err.message}). Proceeding with verification...`);
  }
}

log(`[*] Verifying connectivity against ${httpBaseUrl}/health ...`);

// Prepare HTTP Health Check
const healthUrl = new URL(`${httpBaseUrl}/health`);
const isHttps = healthUrl.protocol === 'https:';
const clientLib = isHttps ? https : http;

const headers = {
  'User-Agent': 'OpenClaw-Skill-Registration/1.0',
};
if (clientId) headers['CF-Access-Client-Id'] = clientId;
if (clientSecret) headers['CF-Access-Client-Secret'] = clientSecret;

const req = clientLib.get(healthUrl, { headers, timeout: 8000 }, (res) => {
  let body = '';
  res.on('data', (d) => (body += d));
  res.on('end', async () => {
    let healthData = {};
    try {
      healthData = JSON.parse(body);
    } catch {
      // Body was not JSON
    }

    if (res.statusCode === 200) {
      log(`[✓] HTTP Health check succeeded!`);

      // Verify WebSocket if ws is installed
      let wsSuccess = null;
      let wsMessage = 'Skipped (ws module not found)';

      if (WebSocket) {
        log(`[*] Probing WebSocket stream at ${wsBaseUrl} ...`);
        try {
          await new Promise((resolve) => {
            const wsHeaders = {};
            if (clientId) wsHeaders['CF-Access-Client-Id'] = clientId;
            if (clientSecret) wsHeaders['CF-Access-Client-Secret'] = clientSecret;

            const wsClient = new WebSocket(wsBaseUrl, { headers: wsHeaders, timeout: 5000 });
            let timer = setTimeout(() => {
              wsClient.close();
              wsSuccess = false;
              wsMessage = 'WebSocket connection timed out';
              resolve();
            }, 4000);

            wsClient.on('open', () => {
              clearTimeout(timer);
              wsSuccess = true;
              wsMessage = 'Connected and handshake confirmed';
              wsClient.close();
              resolve();
            });

            wsClient.on('error', (err) => {
              clearTimeout(timer);
              wsSuccess = false;
              wsMessage = err.message;
              resolve();
            });
          });
        } catch (wsErr) {
          wsSuccess = false;
          wsMessage = wsErr.message;
        }
      }

      const result = {
        success: true,
        message: 'VS Code Stdio Monitor registered and verified successfully!',
        endpoints: {
          httpUrl: httpBaseUrl,
          wsUrl: wsBaseUrl,
        },
        health: {
          status: healthData.status || 'healthy',
          tmuxSession: healthData.tmuxSession || 'agent-session',
          ptyActive: healthData.ptyActive ?? true,
          uptimeSeconds: healthData.uptimeSeconds || 0,
        },
        websocketProbe: {
          passed: wsSuccess,
          detail: wsMessage,
        },
        savedTo: checkOnly ? null : envPath,
      };

      log(`[✓] SUCCESS: Skill registered and ready for OpenClaw chat interactions!`);
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    } else {
      const errResult = {
        success: false,
        statusCode: res.statusCode,
        error: `Server returned HTTP ${res.statusCode}`,
        body: body.substring(0, 500),
      };
      errorLog(`[!] Registration verification failed (HTTP ${res.statusCode}): ${body}`);
      console.log(JSON.stringify(errResult, null, 2));
      process.exit(1);
    }
  });
});

req.on('error', (err) => {
  const errResult = {
    success: false,
    error: `Connection error: ${err.message}`,
    hint: 'Check if the VS Code Monitor bridge is running and reachable.',
  };
  errorLog(`[✗] Connection error: ${err.message}`);
  console.log(JSON.stringify(errResult, null, 2));
  process.exit(1);
});

req.on('timeout', () => {
  req.destroy();
  const errResult = {
    success: false,
    error: 'Request timed out after 8000ms',
    hint: 'Check firewall, domain resolution, or Cloudflare Access policies.',
  };
  errorLog('[✗] Request timed out.');
  console.log(JSON.stringify(errResult, null, 2));
  process.exit(1);
});
